### PR TITLE
API Added fileID and record variables to onBulkUpload hook (Revision 2)

### PR DESCRIPTION
**Pull request by mooror**
## Description

This PR adds the $fileID and $record variables to the "onBulkUpload" extension point that is in the createDataObject() method (in BulkUploadHandler.php). This allows developers to easily set additional fields on the newly created records and use data from the uploaded file to do so. 

See the related issue for a usage example

## Issues

- #296

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

## Replaces
- #297 (Initial PR)
- #302 (Revision 1)

### CODE REVIEW

**Comment by mooror** [comment]
Let me know if this PR needs tests. I have never done one before, but I am willing to learn if needed

**Comment by GuySartorelli** [comment]
Thanks for doing that.
No tests needed - everything that already worked will still work, this just gives some additional arguments that people can opt into using when they implement the `onBulkUpload` extension hook method.

**Review by GuySartorelli — APPROVED** [review]
LGTM

**Comment by mooror** [comment]
> Thanks for doing that. No tests needed - everything that already worked will still work, this just gives some additional arguments that people can opt into using when they implement the `onBulkUpload` extension hook method.

Sounds good :+1:

**Pull request merged**
