### PR TITLE
FIX `HTTPBulkToolsResponse.addSuccessRecords()` fn

### PR DESCRIPTION
**Pull request by pschiffe**
## Description

This function was trying to merge 2 arrays with PHP fn `array_push()` which was failing if the second parameter was array as well. This fix replaces `array_push()` with `array_merge()` fn.

## Manual testing steps

See the linked issue.

## Issues

- #187

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [ ] CI is green

### CODE REVIEW

**Comment by pschiffe** [comment]
Hm, I don't really have any special config I think:

```php
class A extends DataObject {

    private static $many_many = array(
        'B' => 'B',
    );

    public function getCMSFields() {
        $fields = parent::getCMSFields();

        if ($this->exists()) {
            $bulkManager = new BulkManager();
            $bulkManager->removeBulkAction(EditHandler::class);
            $bulkManager->removeBulkAction(DeleteHandler::class);

            $config = $fields->dataFieldByName('B')->getConfig();
            $config->addComponent($bulkManager);
            $config->getComponentByType(GridFieldAddExistingAutocompleter::class)
                ->setSearchList(B::get());
            $fields->dataFieldByName('B')->setConfig($config);
        }

        return $fields;
    }
```

Does this help?

**Comment by GuySartorelli** [comment]
That might help, but what I really need are steps to follow.
From a fresh installation of Silverstripe CMS with this module, what steps do I need to take to trigger the original error?

**Comment by pschiffe** [comment]
In the admin, I see this error when I try to unlink one or more instances of `B` class from `A` class, via the `BulkManager`.

**Comment by GuySartorelli** [comment]
I had to set up the following in order to follow those steps:

<details>
<summary>expand to see code</summary>

This is similar to what you had, but with missing use statements and closing brace
```php
namespace App;

use Colymba\BulkManager\BulkAction\DeleteHandler;
use Colymba\BulkManager\BulkAction\EditHandler;
use Colymba\BulkManager\BulkManager;
use SilverStripe\Forms\GridField\GridFieldAddExistingAutocompleter;
use SilverStripe\ORM\DataObject;

class A extends DataObject
{
    private static $many_many = [
        'B' => B::class,
    ];

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        if ($this->isInDB()) {
            $bulkManager = new BulkManager();
            $bulkManager->removeBulkAction(EditHandler::class);
            $bulkManager->removeBulkAction(DeleteHandler::class);

            $config = $fields->dataFieldByName('B')->getConfig();
            $config->addComponent($bulkManager);
            $config->getComponentByType(GridFieldAddExistingAutocompleter::class)
                ->setSearchList(B::get());
            $fields->dataFieldByName('B')->setConfig($config);
        }

        return $fields;
    }
}
```

I also needed a `B` class that you reference but didn't include, and a model admin for these. Thankfully in this case winging it worked out, but if this hadn't worked I would have had to ask for more information again. It's always better for you to include what you think is too much information, rather than potentially not including enough ;p

```php
namespace App;

use SilverStripe\ORM\DataObject;

class B extends DataObject
{

}
```

```php
namespace App;

use SilverStripe\Admin\ModelAdmin;

class AlphabetAdmin extends ModelAdmin
{
    private static $url_segment = 'alphabet';
    private static $menu_title = 'ALPHABET';

    private static $managed_models = [
        A::class,
        B::class,
    ];
}
```

</details>

With that I can both reproduce the original error and see that the PR resolves it.

**Review by GuySartorelli — APPROVED** [review]
Looks good to me. Works well locally.
It's a little concerning that this is a bug in the CMS 4 version of the module and hasn't bothered anyone enough to fix until now. 😅

We really need to add tests to this module. If you'd like to tackle that I'd definitely support you in it.

In the meantime, thanks a bunch for fixing this!

**Comment by GuySartorelli** [comment]
Failed JS CI job is unrelated to PR changes.

**Comment by pschiffe** [comment]
Thank you @GuySartorelli for your time working on this as well for the feedback on my PR, I really appreciate it.
I'm not really a developer anymore, just trying to update one small project I did long time ago :-)

**Pull request merged**
