### PR TITLE
API lack of phing is now a warning not an error

### LINKED ISSUE #107: BUG i18nTextCollector fails on a project with gridfield-bulk-editing-tools installed.
i18nTextCollector fails if phing is not installed and in the global path, however phing is not marked as a dependency in composer https://github.com/colymba/GridFieldBulkEditingTools/blob/master/composer.json

This doesn't matter if we are running textcollector on this module or not (I was just running this on another module in the same project).

I suggest that we change `require_once` to `include_once` and put a `if(!class_exists('Task')) return;` following, to turn this critical error into a non-critical one.

Buildtools is on the way out, by the way, and we are looking to stop using phing for any internal release processes anymore. :) I've been working on https://github.com/tractorcow/cow as a replacement.

```
  ERR  PHP Fatal error:  require_once(): Failed opening required 'phing/Task.php' (include_path='/Users/dmooyman/Sites/project/vendor/phpunit/phpunit-mock-objects:/Users/dmooyman/Sites/project/vendor/phpunit/php-token-stream:/Users/dmooyman/Sites/project/vendor/phpunit/php-code-coverage:/Users/dmooyman/Sites/project/vendor/phpunit/phpunit:/Users/dmooyman/Sites/project/vendor/symfony/yaml:.:/Users/dmooyman/Sites/project/framework:/Users/dmooyman/Sites/project/framework/parsers:/Users/dmooyman/Sites/project/framework/thirdparty:.:/usr/local/Cellar/php55/5.5.27_2/lib/php:/Users/dmooyman/Sites/project/fulltextsearch/thirdparty/solr-php-client') in /Users/dmooyman/Sites/project/gridfield-bulk-editing-tools/tasks/BuildTransifexTranslations.php on line 12
  ERR  PHP Stack trace:
  ERR  PHP   1. {main}() /Users/dmooyman/Sites/project/framework/cli-script.php:0
  ERR  PHP   2. Director::direct() /Users/dmooyman/Sites/project/framework/cli-script.php:121
  ERR  PHP   3. Director::handleRequest() /Users/dmooyman/Sites/project/framework/control/Director.php:153
  ERR  PHP   4. Controller->handleRequest() /Users/dmooyman/Sites/project/framework/control/Director.php:370
  ERR  PHP   5. RequestHandler->handleRequest() /Users/dmooyman/Sites/project/framework/control/Controller.php:153
  ERR  PHP   6. Controller->handleRequest() /Users/dmooyman/Sites/project/framework/control/RequestHandler.php:222
  ERR  PHP   7. RequestHandler->handleRequest() /Users/dmooyman/Sites/project/framework/control/Controller.php:153
  ERR  PHP   8. Controller->handleAction() /Users/dmooyman/Sites/project/framework/control/RequestHandler.php:200
  ERR  PHP   9. RequestHandler->handleAction() /Users/dmooyman/Sites/project/framework/control/Controller.php:194
  ERR  PHP  10. TaskRunner->runTask() /Users/dmooyman/Sites/project/framework/control/RequestHandler.php:288
  ERR  PHP  11. i18nTextCollectorTask->run() /Users/dmooyman/Sites/project/framework/dev/TaskRunner.php:84
  ERR  PHP  12. i18nTextCollector->run() /Users/dmooyman/Sites/project/framework/tasks/i18nTextCollectorTask.php:57
  ERR  PHP  13. i18nTextCollector->collect() /Users/dmooyman/Sites/project/framework/i18n/i18nTextCollector.php:116
  ERR  PHP  14. i18nTextCollector->getEntitiesByModule() /Users/dmooyman/Sites/project/framework/i18n/i18nTextCollector.php:173
  ERR  PHP  15. i18nTextCollector->processModule() /Users/dmooyman/Sites/project/framework/i18n/i18nTextCollector.php:319
  ERR  PHP  16. i18nTextCollector->collectFromEntityProviders() /Users/dmooyman/Sites/project/framework/i18n/i18nTextCollector.php:368
  ERR  PHP  17. class_exists() /Users/dmooyman/Sites/project/framework/i18n/i18nTextCollector.php:545
  ERR  PHP  18. spl_autoload_call() /Users/dmooyman/Sites/project/framework/i18n/i18nTextCollector.php:545
  ERR  PHP  19. SS_ClassLoader->loadClass() /Users/dmooyman/Sites/project/framework/i18n/i18nTextCollector.php:545
  ERR  PHP  20. require_once() /Users/dmooyman/Sites/project/framework/core/manifest/ClassLoader.php:77
  ERR  
  RES  255 Command did not run successfully
  ```

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #107

### CODE REVIEW

**Comment by tractorcow** [comment]
Thanks ;d

**Comment by colymba** [comment]
thank you! :smile:

**Comment by tractorcow** [comment]
@colymba could we please have a stable tag with this fix in it? :P I'd like to include it in the CWP release this month.

**Comment by colymba** [comment]
Here you go, 2.1.3 should do it.
https://github.com/colymba/GridFieldBulkEditingTools/releases/tag/v2.1.3

**Comment by tractorcow** [comment]
Yay epic.

**Pull request merged**
