### PR TITLE
Added fileID and record variables to onBulkUpload hook

### PR DESCRIPTION
**Pull request by mooror**
This PR adds the $fileID and $record variables to the "onBulkUpload" extension point that is in the createDataObject() method (in BulkUploadHandler.php). This allows developers to easily set additional fields on the newly created records and use data from the uploaded file to do so. 

See the related issue for a usage example

## Issues

- #296

## Pull request checklist

- [x] The target branch is correct
    - See [picking the right version](https://docs.silverstripe.org/en/contributing/code/#picking-the-right-version)
- [x] All commits are relevant to the purpose of the PR (e.g. no debug statements, unrelated refactoring, or arbitrary linting)
    - Small amounts of additional linting are usually okay, but if it makes it hard to concentrate on the relevant changes, ask for the unrelated changes to be reverted, and submitted as a separate PR.
- [x] The commit messages follow our [commit message guidelines](https://docs.silverstripe.org/en/contributing/code/#commit-messages)
- [x] The PR follows our [contribution guidelines](https://docs.silverstripe.org/en/contributing/code/)
- [x] Code changes follow our [coding conventions](https://docs.silverstripe.org/en/contributing/coding_conventions/)
- [x] This change is covered with tests (or tests aren't necessary for this change)
- [x] Any relevant User Help/Developer documentation is updated; for impactful changes, information is added to the changelog for the intended release
- [x] CI is green

### CODE REVIEW

**Comment by GuySartorelli** [comment]
There are a lot of commits on here that aren't related to your change, which are pull in from a merge.
As discussed on slack, please do one of the following:
1. Close this PR, and start again using the `4` branch as a base
2. [reset your commits](https://gist.github.com/GuySartorelli/74627843aeb75e12b777b1f44cb22d2f)

**Comment by GuySartorelli** [comment]
Please also check that you have read the checkbox information and applied it correctly - for example you've ticked "CI is green" but CI hasn't even run. This makes it hard to trust that you've even looked at any of the information in the checkboxes.

**Comment by mooror** [comment]
Oh I thought the "This branch has no conflicts with the base branch" was apart of the CI.

For future reference, how can I tell when the CI has run and if its green?

**Comment by GuySartorelli** [comment]
Right now you'll see something like this (not exactly the same but it should tell you something's awaiting approval)
image

When CI has passed, it'll literally be green and say "All checks have passed"
image

The favicon should also have a green tick when CI has passed and is green.

**Comment by mooror** [comment]
Oh Okay thank you

**Comment by GuySartorelli** [comment]
@mooror Just a reminder to please fix this PR as per https://github.com/colymba/GridFieldBulkEditingTools/pull/297#issuecomment-2254659948

**Comment by GuySartorelli** [comment]
@mooror FYI we're tagging the beta for the next minor release next week - if this doesn't get merged before then it'll be another 6 months before the next release.

**Comment by mooror** [comment]
Oh thanks for the reminders. I will try to get this done today

**Comment by mooror** [comment]
Replaced by #302

**Comment by mooror** [comment]
#302 had a commit that was named incorrectly, so I changed it and created a new PR (#303)

**Pull request closed without merging**
