### PR TITLE
Bulk Manager - Bulk Add Handler

### PR DESCRIPTION
**Pull request by chtombleson**
Added a new handler that allows the bulk creation of data objects.

### CODE REVIEW

**Comment by colymba** [comment]
Seems your commit is reversing this one https://github.com/colymba/GridFieldBulkEditingTools/pull/106 did you rebase against master?

**Comment by chtombleson** [comment]
@colymba It was rebased against master.

**Comment by colymba** [comment]
umm... can you double check your branch was up to date and see if you can resubmit your PR without overriding https://github.com/colymba/GridFieldBulkEditingTools/pull/106? Would be good to get this merged :)

**Comment by robbieaverill** [comment]
Feel free to reopen if you'd like to revisit this PR @chtombleson - thanks for contributing!

**Pull request closed without merging**
