### PR TITLE
FIX: onBulkUpload should be called before write to bypass validation

### PR DESCRIPTION
**Pull request by a2nt**
Some objects has required fields and object validation will fail on write()

### CODE REVIEW

**Comment by GuySartorelli** [comment]
I'm not convinced this _should_ bypass validation... what's your reasoning there?

**Comment by a2nt** [comment]
Well when you create objects using bulk upload you want be able to add data to fields. First u need to upload bunch of images and after then u will be able to edit it

**Comment by GuySartorelli** [comment]
Ahh, okay, it sounds like there's some context I'm missing here. Can you please create an issue for this PR with all of the relevant context and some reproduction steps? That way I will be able to reproduce the bug you're trying to fix and validate that this PR fixes it.

**Comment by GuySartorelli** [comment]
It seems like there's going to be no further activity on this pull request, so we’ve closed it for now. Please open an issue describing the problem if you want to re-approach this work, and we can discuss it from there.

**Pull request closed without merging**
