### PR TITLE
Enhancement: SilverStripe 4 compatibility

### PR DESCRIPTION
**Pull request by robbieaverill**
Enhancement: SilverStripe 4 compatibility

This is a work in progress, but provides a usable start for a 4.x upgrade.

There is still some work that needs to be done on the user interface. Some things (like the edit pencils on the GridField rows) appear to have been replaced in the SS4 framework, and  bootstrap theming should now be applied everywhere. I've started this for the BulkManager.

## Summary

* Implemented PSR-4 autoloader for each of the BulkManager and BulkUpload sections of this module
* Added and implemented namespacing throughout
* Adjusted framework API changes as required (e.g. `SS_HTTPRequest` -> `HTTPRequest`)
* Applied some basic bootstrap styles to the BulkManager GridField actions
* Update composer requirements
* Update documentation to include namespacing

---

Contributes towards #136 but doesn't bring it quite close enough to "stable" to resolve it.

### CODE REVIEW

**Comment by colymba** [comment]
Thanks @robbieaverill! A quick thought.. would it make sense to clean up all those class names now that we have namespacing? I always thought `GridFieldBulkActionDeleteHandler` for example was overly long, and this would give us the opportunity to clean/tidy up those names...

Something like....
GridFieldBulkActionDeleteHandler: `Colymba\BulkManager\BulkAction\DeleteHandler`
GridFieldBulkActionEditHandler: `Colymba\BulkManager\BulkAction\EditHandler`
GridFieldBulkActionHandler: `Colymba\BulkManager\BulkAction\Handler`
GridFieldBulkActionUnlinkHandler: `Colymba\BulkManager\BulkAction\UnlinkHandler`
GridFieldBulkManager: `Colymba\BulkManager\BulkActionManager`

BulkUploadField: `Colymba\BulkUpload\BulkUploadField`
GridFieldBulkImageUpload: [deprecated]
GridFieldBulkUpload: `Colymba\BulkUpload\BulkUploader`
GridFieldBulkUpload_Request: `Colymba\BulkUpload\BulkUploaderRequest`

what do you think?

**Comment by robbieaverill** [comment]
@colymba - yeah, I think it makes sense to shorten the names where you can. Will update now.

**Comment by robbieaverill** [comment]
It's worth noting here that the bulk upload form is possibly not working. If I have some time I will look into adjusting it, but I don't imagine it will take much work. The bulk manager seems to be OK, and both parts are rendering on page load.

They'll both likely need some styling tweaks to suit the new bootstrap theme in the CMS.

**Comment by robbieaverill** [comment]
Hey @colymba - how do you feel about the updated version?

**Comment by colymba** [comment]
@robbieaverill sorry am not following up more actively.... I feel good about the update... I need to test it, but this will be good for the module no matter what.

I had a question about the build.xml file, I saw this got deleted... Phing is probably old school now and I always wanted to replace it with a Gulp or Grunt task. And since SS4 is now using npm too, should we just delete the tasks folder altogether and I'll upgrade this later?

**Comment by robbieaverill** [comment]
Hey @colymba - sorry, I'm not overly familiar with the system, but @tractorcow mentioned it was not used any more so I figured it could be deleted

**Comment by colymba** [comment]
Hey @robbieaveril, I've done some local testing and the switch to SS 4 needs a lot of cosmetics :) The BulkManager seems to basically work, pending more in depth testing, which is great.

The BulkUploader on the other hand, like you said earlier, needs a lot of work. I've got a crude version working for basic upload. Getting this to work also involves switching to https://github.com/silverstripe/silverstripe-asset-admin which I believe the Framework is doing (https://github.com/silverstripe/silverstripe-framework/issues/6481).

**Comment by robbieaverill** [comment]
Hey @colymba - yeah. To be transparent, my reasons for this pull request are that I need to upgrade modules that depend on this one :) this is why I've sort of got it to a usable state without trying to make it perfect.

Re: the uploader, you will probably need to make some changes for the asset abstraction that has been implemented ([see here](https://docs.silverstripe.org/en/4/changelogs/4.0.0/#upgrading-code-that-writes-to-file-dataobjects-or-writes-files-to-the-assets-folder)).

**Comment by tractorcow** [comment]
@colymba we're building a new i18n / text collection system in 4.0; Might be worth looking at porting this module over to using cow. https://github.com/silverstripe/cow/tree/1#module-level-commands

**Comment by colymba** [comment]
thanks @tractorcow I'll be sure to take a look and see what I can do.

@robbieaverill I'll merge this and push another commit for the BulkUploader so we have everything in some sorts of working order. Then I'll work on polishing it.

**Comment by tractorcow** [comment]
Also check out https://github.com/silverstripe/silverstripe-framework/pull/6558; You can probably write something symfony specific if you want to roll your own text collector / localisations. :)

**Pull request merged**
