### PR TITLE
Add the whole record to the has_many realtion

### PR DESCRIPTION
**Pull request by TheBnl**
In my SS 3.4 install the record does not get linked when only the ID is given

### CODE REVIEW

**Comment by colymba** [comment]
That's weird that passing the ID wouldn't work, the SS api should work with both ID or object.
Was there any errors?

**Comment by TheBnl** [comment]
Hey, thanks for the great module!
There where no errors. And the upload action does finishes, creates the Image Object and DataObject, but does not set the parent relation ID on those objects. I can investigate further, i must add that this is the first time i encountered the issue, but adding the whole object instead of just the ID did fix the issue.

**Comment by colymba** [comment]
Just sounds suspicious this never came up before and the api hasn't changed...
Could it be an oversight, like missing has_one for the has_many, forgot to build or something with the module config? Would you be able to post your code?

**Comment by colymba** [comment]
OK, seems there is something going wrong in the `$this->gridField->list->add($record->ID);`, maybe it is fetching the record again before the previous write finished.... maybe....

Anyway, I don't think we need the `$record->write();` that are immediately before the `add()` statements, since there is a write call in `add()` too. 

If you can remove those unnecessary `$record->write();` that would be great, and then could you squash your commits so this can be merged.

Thanks!

**Comment by bummzack** [comment]
Can this be merged, please? I'd really prefer a working module over the `$record->write()` overhead.
Btw.: Merging of the commits can be done directly on GitHub (via option on "Merge" button).

**Comment by TheBnl** [comment]
I haven't gotten around to it, but I can make some time tomorrow. Will remove the writes, think I placed those there to make sure that the ID was set or not.

**Comment by colymba** [comment]
Thanks @TheBnl!

**Comment by TheBnl** [comment]
Thanks! 😄

**Comment by christopherdarling** [comment]
could we get a new release now this has been merged?

**Comment by colymba** [comment]
@christopherdarling here you go 2.1.7 https://github.com/colymba/GridFieldBulkEditingTools/releases/tag/v2.1.7

**Comment by christopherdarling** [comment]
Thanks @colymba  👍

**Comment by hailwood** [comment]
@colymba After the 2.1.7 release I've noticed that our DataObjects are no longer getting the relation ID set (it's stored as 0). Could this commit be at fault? 2.1.8 has the same issue but it started here...

**Comment by TheBnl** [comment]
Maybe it has to do with the removed `$record->write();` calls? Though I dit check it out with a has_many and a many_many relation. Do you keep the problem when you add those back?

**Comment by colymba** [comment]
@hailwood can you confirm this is (only) happening on a `ManyManyList`? Checking the SS API, `HasManyList::add` will call a `write` on the DataObject but not the `ManyManyList`.

So like @TheBnl mentioned, maybe we need to bring back those `write()` calls before the `add()`...

**Pull request merged**
