### PR TITLE
Add italian translation

### PR DESCRIPTION
**Pull request by digitall-it**

### CODE REVIEW

**Comment by colymba** [comment]
thanks @digitall-it. translations are managed through transifex here https://www.transifex.com/colymba/gridfieldbulkeditingtools/

Are you able to send your translations there?

**Comment by digitall-it** [comment]
Requested italian language.

**Comment by colymba** [comment]
Italian has been added on transifex. Just need to join in as contributor.
Thanks!

**Comment by digitall-it** [comment]
Requested to join as contributor to italian team.

**Comment by colymba** [comment]
I'll leave this open as a reminder to pull the translations when ready....

**Comment by digitall-it** [comment]
Italian translation submitted on transifex.

**Comment by colymba** [comment]
translations are pulled and updated. also added a new release with those.
thanks!

**Pull request closed without merging**
